import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Dummy from "./Dummy";
import slug from "./blogpost/[slug]";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
          {`
          
          .center{
            justify-content : center
          }
          .hackor{
            margin-top: 80px;
            border-radius: 10px;
          }
          `}
      </style>
      
      <main className={`${styles.main} ${inter.className} `}>
        {/* <Dummy/> */}
        {/* <div className="dummy">hellor</div> */}
        <div className="{styles.center} justify-center" >
          <p className="center">
            <h1>
              Hunting Coder
            </h1>
          </p>
        </div>
            <p>
            <h3>
              A blogging website for hunting coders by hunting coders 
            </h3>
          </p>

          <img src="/Screenshot 2024-03-21 at 7.27.07 PM.png" alt="hello" width={700} height= {400} className="hackor"/>
        
      </main>
    </>
  );
}
